include: package:lint/analysis_options.yaml

linter:
  rules:
    always_declare_return_types: true
    avoid_unnecessary_containers: true
    sort_constructors_first: true
    prefer_single_quotes: true
    public_member_api_docs: false
    always_put_required_named_parameters_first: true
    avoid_classes_with_only_static_members: true
    always_require_non_null_named_parameters: true
    annotate_overrides: true
    avoid_empty_else: true
    avoid_init_to_null: true
    avoid_relative_lib_imports: true
    avoid_returning_null: true
    avoid_returning_null_for_future: true
    avoid_returning_null_for_void: true
    avoid_returning_this: true
    avoid_types_as_parameter_names: true
    null_closures: true
    avoid_unused_constructor_parameters: true
    no_logic_in_create_state: true
    camel_case_types: true
    avoid_void_async: true
    avoid_equals_and_hash_code_on_mutable_classes: true
    always_specify_types: true
    lines_longer_than_80_chars: false
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_interpolation_to_compose_strings: true
    prefer_spread_collections: true
    prefer_typing_uninitialized_variables: true
    prefer_void_to_null: true
    test_types_in_equals: true
    type_annotate_public_apis: true
    type_init_formals: true
    unawaited_futures: true
    unnecessary_await_in_return: true
    unnecessary_brace_in_string_interps: true
    unnecessary_const: true
    unnecessary_getters_setters: true
    unnecessary_new: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_overrides: true
    unnecessary_parenthesis: true
    unnecessary_raw_strings: true
    unnecessary_statements: true
    unnecessary_string_escapes: true
    unnecessary_string_interpolations: true
    unnecessary_this: true
    use_function_type_syntax_for_parameters: true
    use_key_in_widget_constructors: true
    use_setters_to_change_properties: true